export const BASE_URL = 'http://122.252.229.27:6067/api'
// export const BASE_URL = 'http://192.168.1.80:1414/api'
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const OPEN_MOBILE_SIDEBAR = 'OPEN_MOBILE_SIDEBAR'
export const MESSAGE_CLEAR = 'MESSAGE_CLEAR'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const SIDE_MENU_REQUEST = 'SIDE_MENU_REQUEST'
export const SIDE_MENU_SUCCESS = 'SIDE_MENU_SUCCESS'
export const SIDE_MENU_ERROR = 'SIDE_MENU_ERROR'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

// Group Masters
export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST'
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS'
export const GROUP_LIST_ERROR = 'GROUP_LIST_ERROR'

export const GROUP_ADD_REQUEST = 'GROUP_ADD_REQUEST'
export const GROUP_ADD_SUCCESS = 'GROUP_ADD_SUCCESS'
export const GROUP_ADD_ERROR = 'GROUP_ADD_ERROR'

export const GROUP_DELETE_REQUEST = 'GROUP_DELETE_REQUEST'
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS'
export const GROUP_DELETE_ERROR = 'GROUP_DELETE_ERROR'

export const GROUP_DETAILS_REQUEST = 'GROUP_DETAILS_REQUEST'
export const GROUP_DETAILS_SUCCESS = 'GROUP_DETAILS_SUCCESS'
export const GROUP_DETAILS_ERROR = 'GROUP_DETAILS_ERROR'

export const GROUP_UPDATE_REQUEST = 'GROUP_UPDATE_REQUEST'
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS'
export const GROUP_UPDATE_ERROR = 'GROUP_UPDATE_ERROR'

export const COMMON_INDUSTRY_TYPE_ERROR = 'COMMON_INDUSTRY_TYPE_ERROR'
export const COMMON_INDUSTRY_TYPE_REQUEST = 'COMMON_INDUSTRY_TYPE_REQUEST'
export const COMMON_INDUSTRY_TYPE_SUCCESS = 'COMMON_INDUSTRY_TYPE_SUCCESS'

export const COMMON_TYPE_COMPANYLIST_ERROR = 'COMMON_TYPE_COMPANYLIST_ERROR'
export const COMMON_TYPE_COMPANYLIST_REQUEST = 'COMMON_TYPE_COMPANYLIST_REQUEST'
export const COMMON_TYPE_COMPANYLIST_SUCCESS = 'COMMON_TYPE_COMPANYLIST_SUCCESS'

export const COMMON_TYPE_COSTCENTER_ERROR = 'COMMON_TYPE_COSTCENTER_ERROR'
export const COMMON_TYPE_COSTCENTER_REQUEST = 'COMMON_TYPE_COSTCENTER_REQUEST'
export const COMMON_TYPE_COSTCENTER_SUCCESS = 'COMMON_TYPE_COSTCENTER_SUCCESS'

// Master : Location - ADD/Edit/update/Delete
export const LOCATION_ADD_ERROR = 'LOCATION_ADD_ERROR'
export const LOCATION_ADD_REQUEST = 'LOCATION_ADD_REQUEST'
export const LOCATION_ADD_SUCCESS = 'LOCATION_ADD_SUCCESS'

export const LOCATION_EDIT_ERROR = 'LOCATION_EDIT_ERROR'
export const LOCATION_EDIT_REQUEST = 'LOCATION_EDIT_REQUEST'
export const LOCATION_EDIT_SUCCESS = 'LOCATION_EDIT_SUCCESS'

export const LOCATION_UPDATE_ERROR = 'LOCATION_UPDATE_ERROR'
export const LOCATION_UPDATE_REQUEST = 'LOCATION_UPDATE_REQUEST'
export const LOCATION_UPDATE_SUCCESS = 'LOCATION_UPDATE_SUCCESS'

export const LOCATION_DELETE_ERROR = 'LOCATION_DELETE_ERROR'
export const LOCATION_DELETE_REQUEST = 'LOCATION_DELETE_REQUEST'
export const LOCATION_DELETE_SUCCESS = 'LOCATION_DELETE_SUCCESS'

//Common Data: Group list
export const GROUP_ONLY_REQUEST = 'GROUP_ONLY_REQUEST'
export const GROUP_ONLY_SUCCESS = 'GROUP_ONLY_SUCCESS'
export const GROUP_ONLY_ERROR = 'GROUP_ONLY_ERROR'



//Common Data: Organisation list
export const COMMON_TYPE_OF_ORG_REQUEST = 'COMMON_TYPE_OF_ORG_REQUEST'
export const COMMON_TYPE_OF_ORG_SUCCESS = 'COMMON_TYPE_OF_ORG_SUCCESS'
export const COMMON_TYPE_OF_ORG_ERROR = 'COMMON_TYPE_OF_ORG_ERROR'


//Common Data: Country list
export const COMMON_TYPE_COUNTRY_REQUEST = 'COMMON_TYPE_COUNTRY_REQUEST'
export const COMMON_TYPE_COUNTRY_SUCCESS = 'COMMON_TYPE_COUNTRY_SUCCESS'
export const COMMON_TYPE_COUNTRY_ERROR = 'COMMON_TYPE_COUNTRY_ERROR'

//Common Data: State list
export const COMMON_TYPE_STATE_REQUEST = 'COMMON_TYPE_STATE_REQUEST'
export const COMMON_TYPE_STATE_SUCCESS = 'COMMON_TYPE_STATE_SUCCESS'
export const COMMON_TYPE_STATE_ERROR = 'COMMON_TYPE_STATE_ERROR'

//Common Data: Currency list
export const COMMON_TYPE_CURR_REQUEST = 'COMMON_TYPE_CURR_REQUEST'
export const COMMON_TYPE_CURR_SUCCESS = 'COMMON_TYPE_CURR_SUCCESS'
export const COMMON_TYPE_CURR_ERROR = 'COMMON_TYPE_CURR_ERROR'

//Common Data: District list
export const COMMON_TYPE_DISTRICT_REQUEST = 'COMMON_TYPE_DISTRICT_REQUEST'
export const COMMON_TYPE_DISTRICT_SUCCESS = 'COMMON_TYPE_DISTRICT_SUCCESS'
export const COMMON_TYPE_DISTRICT_ERROR = 'COMMON_TYPE_DISTRICT_ERROR'

//Common Data: Parent list
export const COMMON_TYPE_PARENT_REQUEST = 'COMMON_TYPE_PARENT_REQUEST'
export const COMMON_TYPE_PARENT_SUCCESS = 'COMMON_TYPE_PARENT_SUCCESS'
export const COMMON_TYPE_PARENT_ERROR = 'COMMON_TYPE_PARENT_ERROR'

//Common Data: Designation dropdownlist
export const COMMON_TYPE_DESIGNATION_REQUEST = 'COMMON_TYPE_DESIGNATION_REQUEST'
export const COMMON_TYPE_DESIGNATION_SUCCESS = 'COMMON_TYPE_DESIGNATION_SUCCESS'
export const COMMON_TYPE_DESIGNATION_ERROR = 'COMMON_TYPE_DESIGNATION_ERROR'

//Common Data: leavingreason dropdownlist
export const COMMON_TYPE_LEAVINGREASON_REQUEST = 'COMMON_TYPE_LEAVINGREASON_REQUEST'
export const COMMON_TYPE_LEAVINGREASON_SUCCESS = 'COMMON_TYPE_LEAVINGREASON_SUCCESS'
export const COMMON_TYPE_LEAVINGREASON_ERROR = 'COMMON_TYPE_LEAVINGREASON_ERROR'

//Common Data: bloodgroup dropdownlist
export const COMMON_TYPE_BLOODGROUP_REQUEST = 'COMMON_TYPE_BLOODGROUP_REQUEST'
export const COMMON_TYPE_BLOODGROUP_SUCCESS = 'COMMON_TYPE_BLOODGROUP_SUCCESS'
export const COMMON_TYPE_BLOODGROUP_ERROR = 'COMMON_TYPE_BLOODGROUP_ERROR'

//Common Data: religion dropdownlist
export const COMMON_TYPE_RELIGION_REQUEST = 'COMMON_TYPE_RELIGION_REQUEST'
export const COMMON_TYPE_RELIGION_SUCCESS = 'COMMON_TYPE_RELIGION_SUCCESS'
export const COMMON_TYPE_RELIGION_ERROR = 'COMMON_TYPE_RELIGION_ERROR'

//Common Data: Employee dropdownlist
export const COMMON_TYPE_EMPLOYEE_REQUEST = 'COMMON_TYPE_EMPLOYEE_REQUEST'
export const COMMON_TYPE_EMPLOYEE_SUCCESS = 'COMMON_TYPE_EMPLOYEE_SUCCESS'
export const COMMON_TYPE_EMPLOYEE_ERROR = 'COMMON_TYPE_EMPLOYEE_ERROR'

//Common Data: working dropdownlist
export const COMMON_TYPE_WORKINGTIME_REQUEST = 'COMMON_TYPE_WORKINGTIME_REQUEST'
export const COMMON_TYPE_WORKINGTIME_SUCCESS = 'COMMON_TYPE_WORKINGTIME_SUCCESS'
export const COMMON_TYPE_WORKINGTIME_ERROR = 'COMMON_TYPE_WORKINGTIME_ERROR'

//Common Data: employeement dropdownlist
export const COMMON_TYPE_EMPLOYEEMENT_REQUEST = 'COMMON_TYPE_EMPLOYEEMENT_REQUEST'
export const COMMON_TYPE_EMPLOYEEMENT_SUCCESS = 'COMMON_TYPE_EMPLOYEEMENT_SUCCESS'
export const COMMON_TYPE_EMPLOYEEMENT_ERROR = 'COMMON_TYPE_EMPLOYEEMENT_ERROR'


//Common Data: FUNCTION dropdownlist
export const COMMON_TYPE_FUNCTION_REQUEST = 'COMMON_TYPE_FUNCTION_REQUEST'
export const COMMON_TYPE_FUNCTION_SUCCESS = 'COMMON_TYPE_FUNCTION_SUCCESS'
export const COMMON_TYPE_FUNCTION_ERROR = 'COMMON_TYPE_FUNCTION_ERROR'

//Common Data: Medium dropdownlist
export const COMMON_TYPE_MEDIUM_REQUEST = 'COMMON_TYPE_MEDIUM_REQUEST'
export const COMMON_TYPE_MEDIUM_SUCCESS = 'COMMON_TYPE_MEDIUM_SUCCESS'
export const COMMON_TYPE_MEDIUM_ERROR = 'COMMON_TYPE_MEDIUM_ERROR'

//Common Data: location dropdownlist
export const COMMON_TYPE_LOCATION_REQUEST = 'COMMON_TYPE_LOCATION_REQUEST'
export const COMMON_TYPE_LOCATION_SUCCESS = 'COMMON_TYPE_LOCATION_SUCCESS'
export const COMMON_TYPE_LOCATION_ERROR = 'COMMON_TYPE_LOCATION_ERROR'

//Common Data: JOB dropdownlist
export const COMMON_TYPE_JOB_REQUEST = 'COMMON_TYPE_JOB_REQUEST'
export const COMMON_TYPE_JOB_SUCCESS = 'COMMON_TYPE_JOB_SUCCESS'
export const COMMON_TYPE_JOB_ERROR = 'COMMON_TYPE_JOB_ERROR'

//Common Data: sub-function list based on function id dropdownlist
export const COMMON_TYPE_SUBFUNCTION_REQUEST = 'COMMON_TYPE_SUBFUNCTION_REQUEST'
export const COMMON_TYPE_SUBFUNCTION_SUCCESS = 'COMMON_TYPE_SUBFUNCTION_SUCCESS'
export const COMMON_TYPE_SUBFUNCTION_ERROR = 'COMMON_TYPE_SUBFUNCTION_ERROR'

//Common Data: paygrade dropdownlist
export const COMMON_TYPE_PAYGRADE_REQUEST = 'COMMON_TYPE_PAYGRADE_REQUEST'
export const COMMON_TYPE_PAYGRADE_SUCCESS = 'COMMON_TYPE_PAYGRADE_SUCCESS'
export const COMMON_TYPE_PAYGRADE_ERROR = 'COMMON_TYPE_PAYGRADE_ERROR'

//Common Data: Role dropdownlist
export const COMMON_TYPE_ROLE_REQUEST = 'COMMON_TYPE_ROLE_REQUEST'
export const COMMON_TYPE_ROLE_SUCCESS = 'COMMON_TYPE_ROLE_SUCCESS'
export const COMMON_TYPE_ROLE_ERROR = 'COMMON_TYPE_ROLE_ERROR'


//Common Data: Leave Type dropdown list
export const COMMON_TYPE_LEAVETYPE_REQUEST = 'COMMON_TYPE_LEAVETYPE_REQUEST'
export const COMMON_TYPE_LEAVETYPE_SUCCESS = 'COMMON_TYPE_LEAVETYPE_SUCCESS'
export const COMMON_TYPE_LEAVETYPE_ERROR = 'COMMON_TYPE_LEAVETYPE_ERROR'

//Common Data: Employee dropdown list
export const COMMON_TYPE_HREMPLOYEE_REQUEST = 'COMMON_TYPE_HREMPLOYEE_REQUEST'
export const COMMON_TYPE_HREMPLOYEE_SUCCESS = 'COMMON_TYPE_HREMPLOYEE_SUCCESS'
export const COMMON_TYPE_HREMPLOYEE_ERROR = 'COMMON_TYPE_HREMPLOYEE_ERROR'


//Company Masters
export const COMPANY_LIST_REQUEST = 'COMPANY_LIST_REQUEST'
export const COMPANY_LIST_SUCCESS = 'COMPANY_LIST_SUCCESS'
export const COMPANY_LIST_ERROR = 'COMPANY_LIST_ERROR'

//Company Add Masters
export const COMPANY_ADD_REQUEST = 'COMPANY_ADD_REQUEST'
export const COMPANY_ADD_SUCCESS = 'COMPANY_ADD_SUCCESS'
export const COMPANY_ADD_ERROR = 'COMPANY_ADD_ERROR'

//Company Edit Masters
export const COMPANY_EDIT_REQUEST = 'COMPANY_EDIT_REQUEST'
export const COMPANY_EDIT_SUCCESS = 'COMPANY_EDIT_SUCCESS'
export const COMPANY_EDIT_ERROR = 'COMPANY_EDIT_ERROR'

//Company Update Masters
export const COMPANY_UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST'
export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS'
export const COMPANY_UPDATE_ERROR = 'COMPANY_UPDATE_ERROR'

//Company Delete Masters
export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST'
export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS'
export const COMPANY_DELETE_ERROR = 'COMPANY_DELETE_ERROR'

//Location Masters
export const LOCATION_LIST_REQUEST = 'LOCATION_LIST_REQUEST'
export const LOCATION_LIST_SUCCESS = 'LOCATION_LIST_SUCCESS'
export const LOCATION_LIST_ERROR = 'LOCATION_LIST_ERROR'

//function Masters
export const FUNCTION_LIST_REQUEST = 'FUNCTION_LIST_REQUEST'
export const FUNCTION_LIST_SUCCESS = 'FUNCTION_LIST_SUCCESS'
export const FUNCTION_LIST_ERROR = 'FUNCTION_LIST_ERROR'

//Functions Add Masters
export const FUNCTION_ADD_REQUEST = 'FUNCTION_ADD_REQUEST'
export const FUNCTION_ADD_SUCCESS = 'FUNCTION_ADD_SUCCESS'
export const FUNCTION_ADD_ERROR = 'FUNCTION_ADD_ERROR'

//Functions Edit Masters
export const FUNCTION_EDIT_REQUEST = 'FUNCTION_EDIT_REQUEST'
export const FUNCTION_EDIT_SUCCESS = 'FUNCTION_EDIT_SUCCESS'
export const FUNCTION_EDIT_ERROR = 'FUNCTION_EDIT_ERROR'

//Functions Update Masters
export const FUNCTION_UPDATE_REQUEST = 'FUNCTION_UPDATE_REQUEST'
export const FUNCTION_UPDATE_SUCCESS = 'FUNCTION_UPDATE_SUCCESS'
export const FUNCTION_UPDATE_ERROR = 'FUNCTION_UPDATE_ERROR'

// funcations delete masters
export const FUNCTION_DELETE_REQUEST = 'FUNCTION_DELETE_REQUEST'
export const FUNCTION_DELETE_SUCCESS = 'FUNCTION_DELETE_SUCCESS'
export const FUNCTION_DELETE_ERROR = 'FUNCTION_DELETE_ERROR'

//subfunction Masters
export const SUBFUNCTION_LIST_REQUEST = 'SUBFUNCTION_LIST_REQUEST'
export const SUBFUNCTION_LIST_SUCCESS = 'SUBFUNCTION_LIST_SUCCESS'
export const SUBFUNCTION_LIST_ERROR = 'SUBFUNCTION_LIST_ERROR'

//subfunction Masters
export const SUBFUNCTION_ADD_REQUEST = 'SUBFUNCTION_ADD_REQUEST'
export const SUBFUNCTION_ADD_SUCCESS = 'SUBFUNCTION_ADD_SUCCESS'
export const SUBFUNCTION_ADD_ERROR = 'SUBFUNCTION_ADD_ERROR'

// subfuncation view
export const SUBFUNCTION_EDIT_REQUEST = 'SUBFUNCTION_EDIT_REQUEST'
export const SUBFUNCTION_EDIT_SUCCESS = 'SUBFUNCTION_EDIT_SUCCESS'
export const SUBFUNCTION_EDIT_ERROR = 'SUBFUNCTION_EDIT_ERROR'

export const SUBFUNCTION_DELETE_REQUEST = 'SUBFUNCTION_DELETE_REQUEST'
export const SUBFUNCTION_DELETE_SUCCESS = 'SUBFUNCTION_DELETE_SUCCESS'
export const SUBFUNCTION_DELETE_ERROR = 'SUBFUNCTION_DELETE_ERROR'

// subfuncation update
export const SUBFUNCTION_UPDATE_REQUEST = 'SUBFUNCTION_UPDATE_REQUEST'
export const SUBFUNCTION_UPDATE_SUCCESS = 'SUBFUNCTION_UPDATE_SUCCESS'
export const SUBFUNCTION_UPDATE_ERROR   = 'SUBFUNCTION_UPDATE_ERROR'

//  configuration
//Relationship
export const RELATIONSHIP_LIST_REQUEST = 'RELATIONSHIP_LIST_REQUEST'
export const RELATIONSHIP_LIST_SUCCESS = 'RELATIONSHIP_LIST_SUCCESS'
export const RELATIONSHIP_LIST_ERROR = 'RELATIONSHIP_LIST_ERROR'

//Organization
export const ORGANIZATION_LIST_REQUEST = 'ORGANIZATION_LIST_REQUEST'
export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_SUCCESS'
export const ORGANIZATION_LIST_ERROR = 'ORGANIZATION_LIST_ERROR'

//Organization Add
export const ORGANIZATION_ADD_REQUEST = 'ORGANIZATION_ADD_REQUEST'
export const ORGANIZATION_ADD_SUCCESS = 'ORGANIZATION_ADD_SUCCESS'
export const ORGANIZATION_ADD_ERROR = 'ORGANIZATION_ADD_ERROR'

//Organization Delete
export const ORGANIZATION_DELETE_REQUEST = 'ORGANIZATION_DELETE_REQUEST'
export const ORGANIZATION_DELETE_SUCCESS = 'ORGANIZATION_DELETE_SUCCESS'
export const ORGANIZATION_DELETE_ERROR = 'ORGANIZATION_DELETE_ERROR'

//Organization Details
export const ORGANIZATION_DETAILS_REQUEST = 'ORGANIZATION_DETAILS_REQUEST'
export const ORGANIZATION_DETAILS_SUCCESS = 'ORGANIZATION_DETAILS_SUCCESS'
export const ORGANIZATION_DETAILS_ERROR   = 'ORGANIZATION_DETAILS_ERROR'

//Organization Update
export const ORGANIZATION_UPDATE_REQUEST = 'ORGANIZATION_UPDATE_REQUEST'
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS'
export const ORGANIZATION_UPDATE_ERROR   = 'ORGANIZATION_UPDATE_ERROR'

//studylevel list
export const STUDYLEVEL_LIST_REQUEST = 'STUDYLEVEL_LIST_REQUEST'
export const STUDYLEVEL_LIST_SUCCESS = 'STUDYLEVEL_LIST_SUCCESS'
export const STUDYLEVEL_LIST_ERROR = 'STUDYLEVEL_LIST_ERROR'

//Study Program list
export const STUDYPROGRAM_LIST_REQUEST = 'STUDYPROGRAM_LIST_REQUEST'
export const STUDYPROGRAM_LIST_SUCCESS = 'STUDYPROGRAM_LIST_SUCCESS'
export const STUDYPROGRAM_LIST_ERROR = 'STUDYPROGRAM_LIST_ERROR'

//Unauthenticated studylevel list
export const STUDYLEVEL_UA_LIST_REQUEST = 'STUDYLEVEL_UA_LIST_REQUEST'
export const STUDYLEVEL_UA_LIST_SUCCESS = 'STUDYLEVEL_UA_LIST_SUCCESS'
export const STUDYLEVEL_UA_LIST_ERROR = 'STUDYLEVEL_UA_LIST_ERROR'

//Unauthenticated Study Program list
export const STUDYPROGRAM_UA_LIST_REQUEST = 'STUDYPROGRAM_UA_LIST_REQUEST'
export const STUDYPROGRAM_UA_LIST_SUCCESS = 'STUDYPROGRAM_UA_LIST_SUCCESS'
export const STUDYPROGRAM_UA_LIST_ERROR = 'STUDYPROGRAM_UA_LIST_ERROR'

//Employeement Type list
export const EMPLOYMENT_LIST_REQUEST = 'EMPLOYMENT_LIST_REQUEST'
export const EMPLOYMENT_LIST_SUCCESS = 'EMPLOYMENT_LIST_SUCCESS'
export const EMPLOYMENT_LIST_ERROR = 'EMPLOYMENT_LIST_ERROR'

//LEAVINGREASON list
export const LEAVINGREASON_LIST_REQUEST = 'LEAVINGREASON_LIST_REQUEST'
export const LEAVINGREASON_LIST_SUCCESS = 'LEAVINGREASON_LIST_SUCCESS'
export const LEAVINGREASON_LIST_ERROR = 'LEAVINGREASON_LIST_ERROR'

//District list
export const DISTRICT_LIST_REQUEST = 'DISTRICT_LIST_REQUEST'
export const DISTRICT_LIST_SUCCESS = 'DISTRICT_LIST_SUCCESS'
export const DISTRICT_LIST_ERROR = 'DISTRICT_LIST_ERROR'

//bloodgroup list
export const BLOODGROUP_LIST_REQUEST = 'BLOODGROUP_LIST_REQUEST'
export const BLOODGROUP_LIST_SUCCESS = 'BLOODGROUP_LIST_SUCCESS'
export const BLOODGROUP_LIST_ERROR = 'BLOODGROUP_LIST_ERROR'

//Relion list
export const RELIGION_LIST_REQUEST = 'RELIGION_LIST_REQUEST'
export const RELIGION_LIST_SUCCESS = 'RELIGION_LIST_SUCCESS'
export const RELIGION_LIST_ERROR = 'RELIGION_LIST_ERROR'

//costcenter list
export const COSTCENTER_LIST_REQUEST = 'COSTCENTER_LIST_REQUEST'
export const COSTCENTER_LIST_SUCCESS = 'COSTCENTER_LIST_SUCCESS'
export const COSTCENTER_LIST_ERROR = 'COSTCENTER_LIST_ERROR'

//costcenter add
export const COSTCENTER_ADD_REQUEST = 'COSTCENTER_ADD_REQUEST'
export const COSTCENTER_ADD_SUCCESS = 'COSTCENTER_ADD_SUCCESS'
export const COSTCENTER_ADD_ERROR = 'COSTCENTER_ADD_ERROR'


//costcenter EDIT details
export const COSTCENTER_EDITDETAILS_REQUEST = 'COSTCENTER_EDITDETAILS_REQUEST'
export const COSTCENTER_EDITDETAILS_SUCCESS = 'COSTCENTER_EDITDETAILS_SUCCESS'
export const COSTCENTER_EDITDETAILS_ERROR = 'COSTCENTER_EDITDETAILS_ERROR'


//costcenter update details
export const COSTCENTER_UPDATE_REQUEST = 'COSTCENTER_UPDATE_REQUEST'
export const COSTCENTER_UPDATE_SUCCESS = 'COSTCENTER_UPDATE_SUCCESS'
export const COSTCENTER_UPDATE_ERROR = 'COSTCENTER_UPDATE_ERROR'



//costcenter delete
export const COSTCENTER_DELETE_REQUEST = 'COSTCENTER_DELETE_REQUEST'
export const COSTCENTER_DELETE_SUCCESS = 'COSTCENTER_DELETE_SUCCESS'
export const COSTCENTER_DELETE_ERROR = 'COSTCENTER_DELETE_ERROR'

//Industrytype list
export const INDUSTRYTYPE_LIST_REQUEST = 'INDUSTRYTYPE_LIST_REQUEST'
export const INDUSTRYTYPE_LIST_SUCCESS = 'INDUSTRYTYPE_LIST_SUCCESS'
export const INDUSTRYTYPE_LIST_ERROR = 'INDUSTRYTYPE_LIST_ERROR'

//Paygrade list
export const PAYGRADE_LIST_REQUEST = 'PAYGRADE_LIST_REQUEST'
export const PAYGRADE_LIST_SUCCESS = 'PAYGRADE_LIST_SUCCESS'
export const PAYGRADE_LIST_ERROR = 'PAYGRADE_LIST_ERROR'

//Paygrade add
export const PAYGRADE_ADD_REQUEST = 'PAYGRADE_ADD_REQUEST'
export const PAYGRADE_ADD_SUCCESS = 'PAYGRADE_ADD_SUCCESS'
export const PAYGRADE_ADD_ERROR = 'PAYGRADE_ADD_ERROR'


//caste list
export const CASTE_LIST_REQUEST = 'CASTE_LIST_REQUEST'
export const CASTE_LIST_SUCCESS = 'CASTE_LIST_SUCCESS'
export const CASTE_LIST_ERROR = 'CASTE_LIST_ERROR'

//caste add
export const CASTE_ADD_REQUEST = 'CASTE_ADD_REQUEST'
export const CASTE_ADD_SUCCESS = 'CASTE_ADD_SUCCESS'
export const CASTE_ADD_ERROR = 'CASTE_ADD_ERROR'   

//Bank list
export const BANK_LIST_REQUEST = 'BANK_LIST_REQUEST'
export const BANK_LIST_SUCCESS = 'BANK_LIST_SUCCESS'
export const BANK_LIST_ERROR = 'BANK_LIST_ERROR'

//Designation list
export const DESIGNATION_LIST_REQUEST = 'DESIGNATION_LIST_REQUEST'
export const DESIGNATION_LIST_SUCCESS = 'DESIGNATION_LIST_SUCCESS'
export const DESIGNATION_LIST_ERROR = 'DESIGNATION_LIST_ERROR'

//Company Common Custom list
export const COMMON_COMPANY_CUSTOM_REQUEST = 'COMMON_COMPANY_CUSTOM_REQUEST'
export const COMMON_COMPANY_CUSTOM_SUCCESS = 'COMMON_COMPANY_CUSTOM_SUCCESS'
export const COMMON_COMPANY_CUSTOM_ERROR = 'COMMON_COMPANY_CUSTOM_ERROR'

//Employee list
export const EMPLOYEE_LIST_REQUEST = 'EMPLOYEE_LIST_REQUEST'
export const EMPLOYEE_LIST_SUCCESS = 'EMPLOYEE_LIST_SUCCESS'
export const EMPLOYEE_LIST_ERROR = 'EMPLOYEE_LIST_ERROR'
    
// Employee add
export const EMPLOYEE_ADD_REQUEST = 'EMPLOYEE_ADD_REQUEST'
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS'
export const EMPLOYEE_ADD_ERROR = 'EMPLOYEE_ADD_ERROR'

// Employee update
export const EMPLOYEE_UPDATE_REQUEST = 'EMPLOYEE_UPDATE_REQUEST'
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS'
export const EMPLOYEE_UPDATE_ERROR   = 'EMPLOYEE_UPDATE_ERROR'

// Employee view by id
export const EMPLOYEE_VIEW_REQUEST = 'EMPLOYEE_VIEW_REQUEST'
export const EMPLOYEE_VIEW_SUCCESS = 'EMPLOYEE_VIEW_SUCCESS'
export const EMPLOYEE_VIEW_ERROR = 'EMPLOYEE_VIEW_ERROR'

// Employee Delete by id
export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST'
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS'
export const EMPLOYEE_DELETE_ERROR = 'EMPLOYEE_DELETE_ERROR'

//WorkTime list
export const WORKTIME_LIST_REQUEST = 'WORKTIME_LIST_REQUEST'
export const WORKTIME_LIST_SUCCESS = 'WORKTIME_LIST_SUCCESS'
export const WORKTIME_LIST_ERROR = 'WORKTIME_LIST_ERROR'

//Country list
export const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST'
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS'
export const COUNTRY_LIST_ERROR = 'COUNTRY_LIST_ERROR'

//State list
export const STATE_LIST_REQUEST = 'STATE_LIST_REQUEST'
export const STATE_LIST_SUCCESS = 'STATE_LIST_SUCCESS'
export const STATE_LIST_ERROR = 'STATE_LIST_ERROR'

//Graph data
export const PIE_GRAPH_REQUEST = 'PIE_GRAPH_REQUEST'
export const PIE_GRAPH_SUCCESS = 'PIE_GRAPH_SUCCESS'
export const PIE_GRAPH_ERROR   = 'PIE_GRAPH_ERROR'

//Jobs List
export const JOB_CONFIG_LIST_REQUEST = 'JOB_CONFIG_LIST_REQUEST'
export const JOB_CONFIG_LIST_SUCCESS = 'JOB_CONFIG_LIST_SUCCESS'
export const JOB_CONFIG_LIST_ERROR   = 'JOB_CONFIG_LIST_ERROR'

//Jobs Add
export const JOB_CONFIG_ADD_REQUEST = 'JOB_CONFIG_ADD_REQUEST'
export const JOB_CONFIG_ADD_SUCCESS = 'JOB_CONFIG_ADD_SUCCESS'
export const JOB_CONFIG_ADD_ERROR   = 'JOB_CONFIG_ADD_ERROR'

//Jobs Edit
export const JOB_CONFIG_EDIT_REQUEST = 'JOB_CONFIG_EDIT_REQUEST'
export const JOB_CONFIG_EDIT_SUCCESS = 'JOB_CONFIG_EDIT_SUCCESS'
export const JOB_CONFIG_EDIT_ERROR   = 'JOB_CONFIG_EDIT_ERROR'

//Jobs Update
export const JOB_CONFIG_UPDATE_REQUEST = 'JOB_CONFIG_UPDATE_REQUEST'
export const JOB_CONFIG_UPDATE_SUCCESS = 'JOB_CONFIG_UPDATE_SUCCESS'
export const JOB_CONFIG_UPDATE_ERROR   = 'JOB_CONFIG_UPDATE_ERROR'

//Jobs Delete
export const JOB_CONFIG_DELETE_REQUEST = 'JOB_CONFIG_DELETE_REQUEST'
export const JOB_CONFIG_DELETE_SUCCESS = 'JOB_CONFIG_DELETE_SUCCESS'
export const JOB_CONFIG_DELETE_ERROR   = 'JOB_CONFIG_DELETE_ERROR'

export const COMMON_TYPE_LOC_FUN_REQUEST = 'COMMON_TYPE_LOC_FUN_REQUEST'
export const COMMON_TYPE_LOC_FUN_SUCCESS = 'COMMON_TYPE_LOC_FUN_SUCCESS'
export const COMMON_TYPE_LOC_FUN_ERROR   = 'COMMON_TYPE_LOC_FUN_ERROR'



//caste Details fot fetch the data by id based
export const CASTE_DETAILS_REQUEST = 'CASTE_DETAILS_REQUEST'
export const CASTE_DETAILS_SUCCESS = 'CASTE_DETAILS_SUCCESS'
export const CASTE_DETAILS_ERROR = 'CASTE_DETAILS_ERROR'

//caste update
export const CASTE_UPDATE_REQUEST = 'CASTE_UPDATE_REQUEST'
export const CASTE_UPDATE_SUCCESS = 'CASTE_UPDATE_SUCCESS'
export const CASTE_UPDATE_ERROR = 'CASTE_UPDATE_ERROR'

//caste update
export const CASTE_DELETE_REQUEST = 'CASTE_DELETE_REQUEST'
export const CASTE_DELETE_SUCCESS = 'CASTE_DELETE_SUCCESS'
export const CASTE_DELETE_ERROR = 'CASTE_DELETE_ERROR'


//Bank add 
export const BANK_ADD_REQUEST = 'BANK_ADD_REQUEST'
export const BANK_ADD_SUCCESS = 'BANK_ADD_SUCCESS'
export const BANK_ADD_ERROR = 'BANK_ADD_ERROR'

//Bank display details
export const BANK_DETAILS_REQUEST = 'BANK_DETAILS_REQUEST'
export const BANK_DETAILS_SUCCESS = 'BANK_DETAILS_SUCCESS'
export const BANK_DETAILS_ERROR = 'BANK_DETAILS_ERROR'

//Bank update
export const BANK_UPDATE_REQUEST = 'BANK_UPDATE_REQUEST'
export const BANK_UPDATE_SUCCESS = 'BANK_UPDATE_SUCCESS'
export const BANK_UPDATE_ERROR = 'BANK_UPDATE_ERROR'

//Bank update
export const BANK_DELETE_REQUEST = 'BANK_DELETE_REQUEST'
export const BANK_DELETE_SUCCESS = 'BANK_DELETE_SUCCESS'
export const BANK_DELETE_ERROR = 'BANK_DELETE_ERROR'


//designation add 
export const DESIGNATION_ADD_REQUEST = 'DESIGNATION_ADD_REQUEST'
export const DESIGNATION_ADD_SUCCESS = 'DESIGNATION_ADD_SUCCESS'
export const DESIGNATION_ADD_ERROR = 'DESIGNATION_ADD_ERROR'

//designation Edit display Details
export const DESIGNATION_DETAILS_REQUEST = 'DESIGNATION_DETAILS_REQUEST'
export const DESIGNATION_DETAILS_SUCCESS = 'DESIGNATION_DETAILS_SUCCESS'
export const DESIGNATION_DETAILS_ERROR = 'DESIGNATION_DETAILS_ERROR'

//designation update
export const DESIGNATION_UPDATE_REQUEST = 'DESIGNATION_UPDATE_REQUEST'
export const DESIGNATION_UPDATE_SUCCESS = 'DESIGNATION_UPDATE_SUCCESS'
export const DESIGNATION_UPDATE_ERROR = 'DESIGNATION_UPDATE_ERROR'

//designation delete
export const DESIGNATION_DELETE_REQUEST = 'DESIGNATION_DELETE_REQUEST'
export const DESIGNATION_DELETE_SUCCESS = 'DESIGNATION_DELETE_SUCCESS'
export const DESIGNATION_DELETE_ERROR = 'DESIGNATION_DELETE_ERROR'

//Paygrade Edit date to display id based
export const PAYGRADE_DETAILS_REQUEST = 'PAYGRADE_DETAILS_REQUEST'
export const PAYGRADE_DETAILS_SUCCESS = 'PAYGRADE_DETAILS_SUCCESS'
export const PAYGRADE_DETAILS_ERROR = 'PAYGRADE_DETAILS_ERROR'

//Paygrade update
export const PAYGRADE_UPDATE_REQUEST = 'PAYGRADE_UPDATE_REQUEST'
export const PAYGRADE_UPDATE_SUCCESS = 'PAYGRADE_UPDATE_SUCCESS'
export const PAYGRADE_UPDATE_ERROR = 'PAYGRADE_UPDATE_ERROR'

//Paygrade update
export const PAYGRADE_DELETE_REQUEST = 'PAYGRADE_DELETE_REQUEST'
export const PAYGRADE_DELETE_SUCCESS = 'PAYGRADE_DELETE_SUCCESS'
export const PAYGRADE_DELETE_ERROR = 'PAYGRADE_DELETE_ERROR'

//Jobs Postion List
export const JOB_POSITION_CONFIG_LIST_REQUEST = 'JOB_POSITION_CONFIG_LIST_REQUEST'
export const JOB_POSITION_CONFIG_LIST_SUCCESS = 'JOB_POSITION_CONFIG_LIST_SUCCESS'
export const JOB_POSITION_CONFIG_LIST_ERROR   = 'JOB_POSITION_CONFIG_LIST_ERROR'

//Jobs Postion Add
export const JOB_POSITION_CONFIG_ADD_REQUEST = 'JOB_POSITION_CONFIG_ADD_REQUEST'
export const JOB_POSITION_CONFIG_ADD_SUCCESS = 'JOB_POSITION_CONFIG_ADD_SUCCESS'
export const JOB_POSITION_CONFIG_ADD_ERROR   = 'JOB_POSITION_CONFIG_ADD_ERROR'

//Jobs Postion edit
export const JOB_POSITION_CONFIG_EDIT_REQUEST = 'JOB_POSITION_CONFIG_EDIT_REQUEST'
export const JOB_POSITION_CONFIG_EDIT_SUCCESS = 'JOB_POSITION_CONFIG_EDIT_SUCCESS'
export const JOB_POSITION_CONFIG_EDIT_ERROR   = 'JOB_POSITION_CONFIG_EDIT_ERROR'

//Jobs Postion update
export const JOB_POSITION_CONFIG_UPDATE_REQUEST = 'JOB_POSITION_CONFIG_UPDATE_REQUEST'
export const JOB_POSITION_CONFIG_UPDATE_SUCCESS = 'JOB_POSITION_CONFIG_UPDATE_SUCCESS'
export const JOB_POSITION_CONFIG_UPDATE_ERROR   = 'JOB_POSITION_CONFIG_UPDATE_ERROR'

//Jobs Postion delete
export const JOB_POSITION_CONFIG_DELETE_REQUEST = 'JOB_POSITION_CONFIG_DELETE_REQUEST'
export const JOB_POSITION_CONFIG_DELETE_SUCCESS = 'JOB_POSITION_CONFIG_DELETE_SUCCESS'
export const JOB_POSITION_CONFIG_DELETE_ERROR   = 'JOB_POSITION_CONFIG_DELETE_ERROR'

//Menu List
export const CUS_MENU_CONFIG_LIST_REQUEST = 'CUS_MENU_CONFIG_LIST_REQUEST'
export const CUS_MENU_CONFIG_LIST_SUCCESS = 'CUS_MENU_CONFIG_LIST_SUCCESS'
export const CUS_MENU_CONFIG_LIST_ERROR   = 'CUS_MENU_CONFIG_LIST_ERROR'

//Menu Edit
export const CUS_MENU_CONFIG_EDIT_REQUEST = 'CUS_MENU_CONFIG_EDIT_REQUEST'
export const CUS_MENU_CONFIG_EDIT_SUCCESS = 'CUS_MENU_CONFIG_EDIT_SUCCESS'
export const CUS_MENU_CONFIG_EDIT_ERROR   = 'CUS_MENU_CONFIG_EDIT_ERROR'

//Menu Update
export const CUS_MENU_CONFIG_UPDATE_REQUEST = 'CUS_MENU_CONFIG_UPDATE_REQUEST'
export const CUS_MENU_CONFIG_UPDATE_SUCCESS = 'CUS_MENU_CONFIG_UPDATE_SUCCESS'
export const CUS_MENU_CONFIG_UPDATE_ERROR   = 'CUS_MENU_CONFIG_UPDATE_ERROR'

//Cost Center based report manager and job data
export const COST_CENTER_RM_JOB_REQUEST = 'COST_CENTER_RM_JOB_REQUEST'
export const COST_CENTER_RM_JOB_SUCCESS = 'COST_CENTER_RM_JOB_SUCCESS'
export const COST_CENTER_RM_JOB_ERROR   = 'COST_CENTER_RM_JOB_ERROR'

//Job postion Request
export const COMMON_TYPE_JOB_POSTION_REQUEST = 'COMMON_TYPE_JOB_POSTION_REQUEST'
export const COMMON_TYPE_JOB_POSTION_SUCCESS = 'COMMON_TYPE_JOB_POSTION_SUCCESS'
export const COMMON_TYPE_JOB_POSTION_ERROR   = 'COMMON_TYPE_JOB_POSTION_ERROR'



// Administration 

// User List 
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_ERROR = 'USER_LIST_ERROR'

// User Add
export const USER_ADD_REQUEST = 'USER_ADD_REQUEST'
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS'
export const USER_ADD_ERROR = 'USER_DELETE_ERROR'
//User delete
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR'

// User details
export const USER_EDITDETAILS_REQUEST = 'USER_EDITDETAILS_REQUEST'
export const USER_EDITDETAILS_SUCCESS = 'USER_EDITDETAILS_SUCCESS'
export const USER_EDITDETAILS_ERROR = 'USER_EDITDETAILS_ERROR'

// User update
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'

//user edit details 2
export const USER_EDITDETAILS_ROLE_REQUEST = 'USER_EDITDETAILS_ROLE_REQUEST'
export const USER_EDITDETAILS_ROLE_SUCCESS = 'USER_EDITDETAILS_ROLE_SUCCESS'
export const USER_EDITDETAILS_ROLE_ERROR = 'USER_EDITDETAILS_ROLE_ERROR'




// Onboarding

// Candidate list
export const CANDIDATE_LIST_REQUEST = 'CANDIDATE_LIST_REQUEST'
export const CANDIDATE_LIST_SUCCESS = 'CANDIDATE_LIST_SUCCESS'
export const CANDIDATE_LIST_ERROR = 'CANDIDATE_LIST_ERROR'

// Candidate Add
export const CANDIDATE_ADD_REQUEST = 'CANDIDATE_ADD_REQUEST'
export const CANDIDATE_ADD_SUCCESS = 'CANDIDATE_ADD_SUCCESS'
export const CANDIDATE_ADD_ERROR = 'CANDIDATE_ADD_ERROR'

//Candidate delete
export const CANDIDATE_DELETE_REQUEST = 'CANDIDATE_DELETE_REQUEST'
export const CANDIDATE_DELETE_SUCCESS = 'CANDIDATE_DELETE_SUCCESS'
export const CANDIDATE_DELETE_ERROR = 'CANDIDATE_DELETE_ERROR'

//Candidate edit details
export const CANDIDATE_EDITDETAILS_REQUEST = 'CANDIDATE_EDITDETAILS_REQUEST'
export const CANDIDATE_EDITDETAILS_SUCCESS = 'CANDIDATE_EDITDETAILS_SUCCESS'
export const CANDIDATE_EDITDETAILS_ERROR = 'CANDIDATE_EDITDETAILS_ERROR'

// Candidate update
export const CANDIDATE_UPDATE_REQUEST = 'CANDIDATE_UPDATE_REQUEST'
export const CANDIDATE_UPDATE_SUCCESS = 'CANDIDATE_UPDATE_SUCCESS'
export const CANDIDATE_UPDATE_ERROR = 'CANDIDATE_UPDATE_ERROR'

// Leave

// LeaveType list
export const LEAVETYPES_LIST_REQUEST = 'LEAVETYPES_LIST_REQUEST'
export const LEAVETYPES_LIST_SUCCESS = 'LEAVETYPES_LIST_SUCCESS'
export const LEAVETYPES_LIST_ERROR = 'LEAVETYPES_LIST_ERROR'

// LEAVETYPES Add
export const LEAVETYPES_ADD_REQUEST = 'LEAVETYPES_ADD_REQUEST'
export const LEAVETYPES_ADD_SUCCESS = 'LEAVETYPES_ADD_SUCCESS'
export const LEAVETYPES_ADD_ERROR = 'LEAVETYPES_ADD_ERROR'

//Leave Types delete
export const LEAVETYPES_DELETE_REQUEST = 'LEAVETYPES_DELETE_REQUEST'
export const LEAVETYPES_DELETE_SUCCESS = 'LEAVETYPES_DELETE_SUCCESS'
export const LEAVETYPES_DELETE_ERROR = 'LEAVETYPES_DELETE_ERROR'

//leavetypes edit details
export const LEAVETYPES_EDITDETAILS_REQUEST = 'LEAVETYPES_EDITDETAILS_REQUEST'
export const LEAVETYPES_EDITDETAILS_SUCCESS = 'LEAVETYPES_EDITDETAILS_SUCCESS'
export const LEAVETYPES_EDITDETAILS_ERROR = 'LEAVETYPES_EDITDETAILS_ERROR'

//LeaveTypes update
export const LEAVETYPES_UPDATE_REQUEST = 'LEAVETYPES_UPDATE_REQUEST'
export const LEAVETYPES_UPDATE_SUCCESS = 'LEAVETYPES_UPDATE_SUCCESS'
export const LEAVETYPES_UPDATE_ERROR = 'LEAVETYPES_UPDATE_ERROR'


// LeaveRequest  list
export const LEAVEREQUEST_LIST_REQUEST = 'LEAVEREQUEST_LIST_REQUEST'
export const LEAVEREQUEST_LIST_SUCCESS = 'LEAVEREQUEST_LIST_SUCCESS'
export const LEAVEREQUEST_LIST_ERROR = 'LEAVEREQUEST_LIST_ERROR'

// LeaveRequest  GRid list
export const LEAVEREQUEST_GRID_LIST_REQUEST = 'LEAVEREQUEST_GRID_LIST_REQUEST'
export const LEAVEREQUEST_GRID_LIST_SUCCESS = 'LEAVEREQUEST_GRID_LIST_SUCCESS'
export const LEAVEREQUEST_GRID_LIST_ERROR   = 'LEAVEREQUEST_GRID_LIST_ERROR'

// LeaveRequest Add
export const LEAVEREQUEST_ADD_REQUEST = 'LEAVEREQUEST_ADD_REQUEST'
export const LEAVEREQUEST_ADD_SUCCESS = 'LEAVEREQUEST_ADD_SUCCESS'
export const LEAVEREQUEST_ADD_ERROR = 'LEAVEREQUEST_ADD_ERROR'

//LeaveRequest delete
export const LEAVEREQUEST_DELETE_REQUEST = 'LEAVEREQUEST_DELETE_REQUEST'
export const LEAVEREQUEST_DELETE_SUCCESS = 'LEAVEREQUEST_DELETE_SUCCESS'
export const LEAVEREQUEST_DELETE_ERROR = 'LEAVEREQUEST_DELETE_ERROR'

//LeaveRequest edit details
export const LEAVEREQUEST_EDITDETAILS_REQUEST = 'LEAVEREQUEST_EDITDETAILS_REQUEST'
export const LEAVEREQUEST_EDITDETAILS_SUCCESS = 'LEAVEREQUEST_EDITDETAILS_SUCCESS'
export const LEAVEREQUEST_EDITDETAILS_ERROR = 'LEAVEREQUEST_EDITDETAILS_ERROR'

//LeaveRequest update
export const LEAVEREQUEST_UPDATE_REQUEST = 'LEAVEREQUEST_UPDATE_REQUEST'
export const LEAVEREQUEST_UPDATE_SUCCESS = 'LEAVEREQUEST_UPDATE_SUCCESS'
export const LEAVEREQUEST_UPDATE_ERROR = 'LEAVEREQUEST_UPDATE_ERROR'


// LeaveAllocations  list
export const LEAVEALLOCATION_LIST_REQUEST = 'LEAVEALLOCATION_LIST_REQUEST'
export const LEAVEALLOCATION_LIST_SUCCESS = 'LEAVEALLOCATION_LIST_SUCCESS'
export const LEAVEALLOCATION_LIST_ERROR = 'LEAVEALLOCATION_LIST_ERROR'

// LeaveAllocations  Add
export const LEAVEALLOCATION_ADD_REQUEST = 'LEAVEALLOCATION_ADD_REQUEST'
export const LEAVEALLOCATION_ADD_SUCCESS = 'LEAVEALLOCATION_ADD_SUCCESS'
export const LEAVEALLOCATION_ADD_ERROR = 'LEAVEALLOCATION_ADD_ERROR'

// LeaveAllocations  Edit
export const LEAVEALLOCATION_EDITDETAILS_REQUEST = 'LEAVEALLOCATION_EDITDETAILS_REQUEST'
export const LEAVEALLOCATION_EDITDETAILS_SUCCESS = 'LEAVEALLOCATION_EDITDETAILS_SUCCESS'
export const LEAVEALLOCATION_EDITDETAILS_ERROR = 'LEAVEALLOCATION_EDITDETAILS_ERROR'

// LeaveAllocations  Update
export const LEAVEALLOCATION_UPDATE_REQUEST = 'LEAVEALLOCATION_UPDATE_REQUEST'
export const LEAVEALLOCATION_UPDATE_SUCCESS = 'LEAVEALLOCATION_UPDATE_SUCCESS'
export const LEAVEALLOCATION_UPDATE_ERROR = 'LEAVEALLOCATION_UPDATE_ERROR'

//LeaveAllocations delete
export const LEAVEALLOCATION_DELETE_REQUEST = 'LEAVEALLOCATION_DELETE_REQUEST'
export const LEAVEALLOCATION_DELETE_SUCCESS = 'LEAVEALLOCATION_DELETE_SUCCESS'
export const LEAVEALLOCATION_DELETE_ERROR = 'LEAVEALLOCATION_DELETE_ERROR'


//Employee Family Members
export const EMP_FAM_ADD_REQUEST = 'EMP_FAM_ADD_REQUEST'
export const EMP_FAM_ADD_SUCCESS = 'EMP_FAM_ADD_SUCCESS'
export const EMP_FAM_ADD_ERROR = 'EMP_FAM_ADD_ERROR'

//Employee Family Members Delete
export const EMP_FAM_DELETE_REQUEST = 'EMP_FAM_DELETE_REQUEST'
export const EMP_FAM_DELETE_SUCCESS = 'EMP_FAM_DELETE_SUCCESS'
export const EMP_FAM_DELETE_ERROR = 'EMP_FAM_DELETE_ERROR'

//Employee Family Members EditDetails
export const EMP_FAM_EDITDETAILS_REQUEST = 'EMP_FAM_EDITDETAILS_REQUEST'
export const EMP_FAM_EDITDETAILS_SUCCESS = 'EMP_FAM_EDITDETAILS_SUCCESS'
export const EMP_FAM_EDITDETAILS_ERROR = 'EMP_FAM_EDITDETAILS_ERROR'

//Employee Family Members UPDATE
export const EMP_FAM_UPDATE_REQUEST = 'EMP_FAM_UPDATE_REQUEST'
export const EMP_FAM_UPDATE_SUCCESS = 'EMP_FAM_UPDATE_SUCCESS'
export const EMP_FAM_UPDATE_ERROR   = 'EMP_FAM_UPDATE_ERROR'


//Employee Working Experience Details
export const EMP_WE_ADD_REQUEST = 'EMP_WE_ADD_REQUEST'
export const EMP_WE_ADD_SUCCESS = 'EMP_WE_ADD_SUCCESS'
export const EMP_WE_ADD_ERROR = 'EMP_WE_ADD_ERROR'

// Delete Employee Working Experience 
export const EMP_WE_DELETE_REQUEST = 'EMP_WE_DELETE_REQUEST'
export const EMP_WE_DELETE_SUCCESS = 'EMP_WE_DELETE_SUCCESS'
export const EMP_WE_DELETE_ERROR = 'EMP_WE_DELETE_ERROR'

// DETAILS Employee Working Experience 
export const EMP_WE_DETAILS_REQUEST = 'EMP_WE_DETAILS_REQUEST'
export const EMP_WE_DETAILS_SUCCESS = 'EMP_WE_DETAILS_SUCCESS'
export const EMP_WE_DETAILS_ERROR = 'EMP_WE_DETAILS_ERROR'

// DETAILS Employee Working Experience 
export const EMP_WE_UPDATE_REQUEST = 'EMP_WE_UPDATE_REQUEST'
export const EMP_WE_UPDATE_SUCCESS = 'EMP_WE_UPDATE_SUCCESS'
export const EMP_WE_UPDATE_ERROR   = 'EMP_WE_UPDATE_ERROR'


//Employee Education add
export const EMP_EDU_ADD_REQUEST = 'EMP_EDU_ADD_REQUEST'
export const EMP_EDU_ADD_SUCCESS = 'EMP_EDU_ADD_SUCCESS'
export const EMP_EDU_ADD_ERROR   = 'EMP_EDU_ADD_ERROR'

//Employee Education edit
export const EMP_EDU_EDITDETAILS_REQUEST = 'EMP_EDU_EDITDETAILS_REQUEST'
export const EMP_EDU_EDITDETAILS_SUCCESS = 'EMP_EDU_EDITDETAILS_SUCCESS'
export const EMP_EDU_EDITDETAILS_ERROR = 'EMP_EDU_EDITDETAILS_ERROR'

//Employee Education Update
export const EMP_EDU_UPDATE_REQUEST = 'EMP_EDU_UPDATE_REQUEST'
export const EMP_EDU_UPDATE_SUCCESS = 'EMP_EDU_UPDATE_SUCCESS'
export const EMP_EDU_UPDATE_ERROR = 'EMP_EDU_UPDATE_ERROR'

//Employee Education DELETE
export const EMP_EDU_DELETE_REQUEST = 'EMP_EDU_DELETE_REQUEST'
export const EMP_EDU_DELETE_SUCCESS = 'EMP_EDU_DELETE_SUCCESS'
export const EMP_EDU_DELETE_ERROR   = 'EMP_EDU_DELETE_ERROR'

//Employee bank Add
export const EMP_BANK_ADD_REQUEST = 'EMP_BANK_ADD_REQUEST'
export const EMP_BANK_ADD_SUCCESS = 'EMP_BANK_ADD_SUCCESS'
export const EMP_BANK_ADD_ERROR = 'EMP_BANK_ADD_ERROR'
    
// /Employee bank Delete
export const EMP_BANK_DELETE_REQUEST = 'EMP_BANK_DELETE_REQUEST'
export const EMP_BANK_DELETE_SUCCESS = 'EMP_BANK_DELETE_SUCCESS'
export const EMP_BANK_DELETE_ERROR = 'EMP_BANK_DELETE_ERROR'

// /Employee bank Edit
export const EMP_BANK_EDITDETAILS_REQUEST = 'EMP_BANK_EDITDETAILS_REQUEST'
export const EMP_BANK_EDITDETAILS_SUCCESS = 'EMP_BANK_EDITDETAILS_SUCCESS'
export const EMP_BANK_EDITDETAILS_ERROR = 'EMP_BANK_EDITDETAILS_ERROR'

// /Employee bank Update
export const EMP_BANK_UPDATE_REQUEST = 'EMP_BANK_UPDATE_REQUEST'
export const EMP_BANK_UPDATE_SUCCESS = 'EMP_BANK_UPDATE_SUCCESS'
export const EMP_BANK_UPDATE_ERROR   = 'EMP_BANK_UPDATE_ERROR'

//Aadhar Image
export const AADHAR_IMG_REQUEST = 'AADHAR_IMG_REQUEST'
export const AADHAR_IMG_SUCCESS = 'AADHAR_IMG_SUCCESS'
export const AADHAR_IMG_ERROR   = 'AADHAR_IMG_ERROR'

//PAN Image
export const PAN_IMG_REQUEST = 'PAN_IMG_REQUEST'
export const PAN_IMG_SUCCESS = 'PAN_IMG_SUCCESS'
export const PAN_IMG_ERROR   = 'PAN_IMG_ERROR'

//User Profile Image
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_ERROR   = 'USER_PROFILE_UPDATE_ERROR'

//Apply Job
export const CANDIDATE_JOB_APPLY_REQUEST = 'CANDIDATE_JOB_APPLY_REQUEST'
export const CANDIDATE_JOB_APPLY_SUCCESS = 'CANDIDATE_JOB_APPLY_SUCCESS'
export const CANDIDATE_JOB_APPLY_ERROR   = 'CANDIDATE_JOB_APPLY_ERROR'

//get Job based on company id
export const COM_JOB_REQUEST = 'COM_JOB_REQUEST'
export const COM_JOB_SUCCESS = 'COM_JOB_SUCCESS'
export const COM_JOB_ERROR = 'COM_JOB_ERROR'


//get user details without authentication
export const CAND_UNUSER_REQUEST = 'CAND_UNUSER_REQUEST'
export const CAND_UNUSER_SUCCESS = 'CAND_UNUSER_SUCCESS'
export const CAND_UNUSER_ERROR   = 'CAND_UNUSER_ERROR'

//get resume parser details without authentication
export const OPEN_RESUME_PARSE_REQUEST = 'OPEN_RESUME_PARSE_REQUEST'
export const OPEN_RESUME_PARSE_SUCCESS = 'OPEN_RESUME_PARSE_SUCCESS'
export const OPEN_RESUME_PARSE_ERROR   = 'OPEN_RESUME_PARSE_ERROR'

//Common Data: Country list for Unauthenticated
export const COMMON_UA_TYPE_COUNTRY_REQUEST = 'COMMON_UA_TYPE_COUNTRY_REQUEST'
export const COMMON_UA_TYPE_COUNTRY_SUCCESS = 'COMMON_UA_TYPE_COUNTRY_SUCCESS'
export const COMMON_UA_TYPE_COUNTRY_ERROR   = 'COMMON_UA_TYPE_COUNTRY_ERROR'

//Common Data: State list for Unauthenticated
export const COMMON_UA_TYPE_STATE_REQUEST = 'COMMON_UA_TYPE_STATE_REQUEST'
export const COMMON_UA_TYPE_STATE_SUCCESS = 'COMMON_UA_TYPE_STATE_SUCCESS'
export const COMMON_UA_TYPE_STATE_ERROR   = 'COMMON_UA_TYPE_STATE_ERROR'

//Common Data: District list for Unauthenticated
export const COMMON_UA_TYPE_DISTRICT_REQUEST = 'COMMON_UA_TYPE_DISTRICT_REQUEST'
export const COMMON_UA_TYPE_DISTRICT_SUCCESS = 'COMMON_UA_TYPE_DISTRICT_SUCCESS'
export const COMMON_UA_TYPE_DISTRICT_ERROR   = 'COMMON_UA_TYPE_DISTRICT_ERROR'


//Workflow Details
export const CANDIDATE_WORKFLOW_REQUEST = 'CANDIDATE_WORKFLOW_REQUEST'
export const CANDIDATE_WORKFLOW_SUCCESS = 'CANDIDATE_WORKFLOW_SUCCESS'
export const CANDIDATE_WORKFLOW_ERROR   = 'CANDIDATE_WORKFLOW_ERROR'

//Candidate Status Update Details
export const CANDIDATE_STATUS_BTN_REQUEST = 'CANDIDATE_STATUS_BTN_REQUEST'
export const CANDIDATE_STATUS_BTN_SUCCESS = 'CANDIDATE_STATUS_BTN_SUCCESS'
export const CANDIDATE_STATUS_BTN_ERROR   = 'CANDIDATE_STATUS_BTN_ERROR'

//Candidate Status Update Details
export const CAND_UNUSER_STATUS_REQUEST = 'CAND_UNUSER_STATUS_REQUEST'
export const CAND_UNUSER_STATUS_SUCCESS = 'CAND_UNUSER_STATUS_SUCCESS'
export const CAND_UNUSER_STATUS_ERROR   = 'CAND_UNUSER_STATUS_ERROR'

//Candidate Status Update Details
export const EMPLOYEE_LIST_UPDATE_HISTORY_REQUEST = 'EMPLOYEE_LIST_UPDATE_HISTORY_REQUEST'
export const EMPLOYEE_LIST_UPDATE_HISTORY_SUCCESS = 'EMPLOYEE_LIST_UPDATE_HISTORY_SUCCESS'
export const EMPLOYEE_LIST_UPDATE_HISTORY_ERROR = 'EMPLOYEE_LIST_UPDATE_HISTORY_ERROR'

// Leave Allocation Workflow status for button action
// FOR Approve button
export const LEAVEALLOCATION_APPROVE_STATUS_REQUEST = 'LEAVEALLOCATION_APPROVE_STATUS_REQUEST'
export const LEAVEALLOCATION_APPROVE_STATUS_SUCCESS = 'LEAVEALLOCATION_APPROVE_STATUS_SUCCESS'
export const LEAVEALLOCATION_APPROVE_STATUS_ERROR = 'LEAVEALLOCATION_APPROVE_STATUS_ERROR'

export const LEAVEALLOCATION_SECONDAPPROVE_STATUS_REQUEST = 'LEAVEALLOCATION_SECONDAPPROVE_STATUS_REQUEST'
export const LEAVEALLOCATION_SECONDAPPROVE_STATUS_SUCCESS = 'LEAVEALLOCATION_SECONDAPPROVE_STATUS_SUCCESS'
export const LEAVEALLOCATION_SECONDAPPROVE_STATUS_ERROR = 'LEAVEALLOCATION_SECONDAPPROVE_STATUS_ERROR'

export const LEAVEALLOCATION_REFUSE_STATUS_REQUEST = 'LEAVEALLOCATION_REFUSE_STATUS_REQUEST'
export const LEAVEALLOCATION_REFUSE_STATUS_SUCCESS = 'LEAVEALLOCATION_REFUSE_STATUS_SUCCESS'
export const LEAVEALLOCATION_REFUSE_STATUS_ERROR = 'LEAVEALLOCATION_REFUSE_STATUS_ERROR'

export const LEAVEALLOCATION_DRAFT_STATUS_REQUEST = 'LEAVEALLOCATION_DRAFT_STATUS_REQUEST'
export const LEAVEALLOCATION_DRAFT_STATUS_SUCCESS = 'LEAVEALLOCATION_DRAFT_STATUS_SUCCESS'
export const LEAVEALLOCATION_DRAFT_STATUS_ERROR = 'LEAVEALLOCATION_DRAFT_STATUS_ERROR'

export const LEAVEALLOCATION_CONFIRM_STATUS_REQUEST = 'LEAVEALLOCATION_CONFIRM_STATUS_REQUEST'
export const LEAVEALLOCATION_CONFIRM_STATUS_SUCCESS = 'LEAVEALLOCATION_CONFIRM_STATUS_SUCCESS'
export const LEAVEALLOCATION_CONFIRM_STATUS_ERROR = 'LEAVEALLOCATION_CONFIRM_STATUS_ERROR'

export const LEAVEALLOCATION_CANCEL_STATUS_REQUEST = 'LEAVEALLOCATION_CANCEL_STATUS_REQUEST'
export const LEAVEALLOCATION_CANCEL_STATUS_SUCCESS = 'LEAVEALLOCATION_CANCEL_STATUS_SUCCESS'
export const LEAVEALLOCATION_CANCEL_STATUS_ERROR = 'LEAVEALLOCATION_CANCEL_STATUS_ERROR'

// Leave Request Workflow status for button action
// FOR Approve button

export const LEAVEREQUEST_APPROVE_STATUS_REQUEST = 'LEAVEREQUEST_APPROVE_STATUS_REQUEST'
export const LEAVEREQUEST_APPROVE_STATUS_SUCCESS = 'LEAVEREQUEST_APPROVE_STATUS_SUCCESS'
export const LEAVEREQUEST_APPROVE_STATUS_ERROR = 'LEAVEREQUEST_APPROVE_STATUS_ERROR'

export const LEAVEREQUEST_SECONDAPPROVE_STATUS_REQUEST = 'LEAVEREQUEST_SECONDAPPROVE_STATUS_REQUEST'
export const LEAVEREQUEST_SECONDAPPROVE_STATUS_SUCCESS = 'LEAVEREQUEST_SECONDAPPROVE_STATUS_SUCCESS'
export const LEAVEREQUEST_SECONDAPPROVE_STATUS_ERROR = 'LEAVEREQUEST_SECONDAPPROVE_STATUS_ERROR'

export const LEAVEREQUEST_REFUSE_STATUS_REQUEST = 'LEAVEREQUEST_REFUSE_STATUS_REQUEST'
export const LEAVEREQUEST_REFUSE_STATUS_SUCCESS = 'LEAVEREQUEST_REFUSE_STATUS_SUCCESS'
export const LEAVEREQUEST_REFUSE_STATUS_ERROR = 'LEAVEREQUEST_REFUSE_STATUS_ERROR'

export const LEAVEREQUEST_DRAFT_STATUS_REQUEST = 'LEAVEREQUEST_DRAFT_STATUS_REQUEST'
export const LEAVEREQUEST_DRAFT_STATUS_SUCCESS = 'LEAVEREQUEST_DRAFT_STATUS_SUCCESS'
export const LEAVEREQUEST_DRAFT_STATUS_ERROR = 'LEAVEREQUEST_DRAFT_STATUS_ERROR'

export const LEAVEREQUEST_CONFIRM_STATUS_REQUEST = 'LEAVEREQUEST_CONFIRM_STATUS_REQUEST'
export const LEAVEREQUEST_CONFIRM_STATUS_SUCCESS = 'LEAVEREQUEST_CONFIRM_STATUS_SUCCESS'
export const LEAVEREQUEST_CONFIRM_STATUS_ERROR = 'LEAVEREQUEST_CONFIRM_STATUS_ERROR'

export const LEAVEREQUEST_CANCELREQUEST_STATUS_REQUEST = 'LEAVEREQUEST_CANCELREQUEST_STATUS_REQUEST'
export const LEAVEREQUEST_CANCELREQUEST_STATUS_SUCCESS = 'LEAVEREQUEST_CANCELREQUEST_STATUS_SUCCESS'
export const LEAVEREQUEST_CANCELREQUEST_STATUS_ERROR = 'LEAVEREQUEST_CANCELREQUEST_STATUS_ERROR'

export const LEAVEREQUEST_CANCELAPPROVAL_STATUS_REQUEST = 'LEAVEREQUEST_CANCELAPPROVAL_STATUS_REQUEST'
export const LEAVEREQUEST_CANCELAPPROVAL_STATUS_SUCCESS = 'LEAVEREQUEST_CANCELAPPROVAL_STATUS_SUCCESS'
export const LEAVEREQUEST_CANCELAPPROVAL_STATUS_ERROR = 'LEAVEREQUEST_CANCELAPPROVAL_STATUS_ERROR'



export const COMMON_TYPE_GET_REPORT_MANAGER_REQUEST   = 'COMMON_TYPE_GET_REPORT_MANAGER_REQUEST'
export const COMMON_TYPE_GET_REPORT_MANAGER_SUCCESS   = 'COMMON_TYPE_GET_REPORT_MANAGER_SUCCESS'
export const COMMON_TYPE_GET_REPORT_MANAGER_ERROR     = 'COMMON_TYPE_GET_REPORT_MANAGER_ERROR'

export const CANDIDATE_UPDATE_ONBOARDING_POPUP_REQUEST   = 'CANDIDATE_UPDATE_ONBOARDING_POPUP_REQUEST'
export const CANDIDATE_UPDATE_ONBOARDING_POPUP_SUCCESS   = 'CANDIDATE_UPDATE_ONBOARDING_POPUP_SUCCESS'
export const CANDIDATE_UPDATE_ONBOARDING_POPUP_ERROR     = 'CANDIDATE_UPDATE_ONBOARDING_POPUP_ERROR'

export const LEAVE_ACCUMULATION_LIST_REQUEST   = 'LEAVE_ACCUMULATION_LIST_REQUEST'
export const LEAVE_ACCUMULATION_LIST_SUCCESS   = 'LEAVE_ACCUMULATION_LIST_SUCCESS'
export const LEAVE_ACCUMULATION_LIST_ERROR     = 'LEAVE_ACCUMULATION_LIST_ERROR'

export const LEAVE_ACCUMULATION_ADD_REQUEST   = 'LEAVE_ACCUMULATION_ADD_REQUEST'
export const LEAVE_ACCUMULATION_ADD_SUCCESS   = 'LEAVE_ACCUMULATION_ADD_SUCCESS'
export const LEAVE_ACCUMULATION_ADD_ERROR     = 'LEAVE_ACCUMULATION_ADD_ERROR'

export const LEAVE_ACCUMULATION_EDIT_REQUEST   = 'LEAVE_ACCUMULATION_EDIT_REQUEST'
export const LEAVE_ACCUMULATION_EDIT_SUCCESS   = 'LEAVE_ACCUMULATION_EDIT_SUCCESS'
export const LEAVE_ACCUMULATION_EDIT_ERROR     = 'LEAVE_ACCUMULATION_EDIT_ERROR'

export const LEAVE_ACCUMULATION_UPDATE_REQUEST   = 'LEAVE_ACCUMULATION_UPDATE_REQUEST'
export const LEAVE_ACCUMULATION_UPDATE_SUCCESS   = 'LEAVE_ACCUMULATION_UPDATE_SUCCESS'
export const LEAVE_ACCUMULATION_UPDATE_ERROR     = 'LEAVE_ACCUMULATION_UPDATE_ERROR'

export const LEAVE_ACCUMULATION_DELETE_REQUEST   = 'LEAVE_ACCUMULATION_DELETE_REQUEST'
export const LEAVE_ACCUMULATION_DELETE_SUCCESS   = 'LEAVE_ACCUMULATION_DELETE_SUCCESS'
export const LEAVE_ACCUMULATION_DELETE_ERROR = 'LEAVE_ACCUMULATION_DELETE_ERROR'

export const LEAVE_ACCUMULATION_STATUS_UPDATE_REQUEST   = 'LEAVE_ACCUMULATION_STATUS_UPDATE_REQUEST'
export const LEAVE_ACCUMULATION_STATUS_UPDATE_SUCCESS   = 'LEAVE_ACCUMULATION_STATUS_UPDATE_SUCCESS'
export const LEAVE_ACCUMULATION_STATUS_UPDATE_ERROR = 'LEAVE_ACCUMULATION_STATUS_UPDATE_ERROR'


// leave Main types

export const LEAVE_MAINTYPES_LIST_REQUEST   = 'LEAVE_MAINTYPES_LIST_REQUEST'
export const LEAVE_MAINTYPES_LIST_SUCCESS   = 'LEAVE_MAINTYPES_LIST_SUCCESS'
export const LEAVE_MAINTYPES_LIST_ERROR     = 'LEAVE_MAINTYPES_LIST_ERROR'

export const LEAVE_MAINTYPES_ADD_REQUEST   = 'LEAVE_MAINTYPES_ADD_REQUEST'
export const LEAVE_MAINTYPES_ADD_SUCCESS   = 'LEAVE_MAINTYPES_ADD_SUCCESS'
export const LEAVE_MAINTYPES_ADD_ERROR     = 'LEAVE_MAINTYPES_ADD_ERROR'

export const LEAVE_MAINTYPES_EDIT_REQUEST   = 'LEAVE_MAINTYPES_EDIT_REQUEST'
export const LEAVE_MAINTYPES_EDIT_SUCCESS   = 'LEAVE_MAINTYPES_EDIT_SUCCESS'
export const LEAVE_MAINTYPES_EDIT_ERROR     = 'LEAVE_MAINTYPES_EDIT_ERROR'

export const LEAVE_MAINTYPES_UPDATE_REQUEST   = 'LEAVE_MAINTYPES_UPDATE_REQUEST'
export const LEAVE_MAINTYPES_UPDATE_SUCCESS   = 'LEAVE_MAINTYPES_UPDATE_SUCCESS'
export const LEAVE_MAINTYPES_UPDATE_ERROR     = 'LEAVE_MAINTYPES_UPDATE_ERROR'

export const LEAVE_MAINTYPES_DELETE_REQUEST   = 'LEAVE_MAINTYPES_DELETE_REQUEST'
export const LEAVE_MAINTYPES_DELETE_SUCCESS   = 'LEAVE_MAINTYPES_DELETE_SUCCESS'
export const LEAVE_MAINTYPES_DELETE_ERROR     = 'LEAVE_MAINTYPES_DELETE_ERROR'

export const EMPLOYEE_EXPORT_REQUEST   = 'EMPLOYEE_EXPORT_REQUEST'
export const EMPLOYEE_EXPORT_SUCCESS   = 'EMPLOYEE_EXPORT_SUCCESS'
export const EMPLOYEE_EXPORT_ERROR     = 'EMPLOYEE_EXPORT_ERROR'

export const EMPLOYEE_IMPORT_REQUEST   = 'EMPLOYEE_IMPORT_REQUEST'
export const EMPLOYEE_IMPORT_SUCCESS   = 'EMPLOYEE_IMPORT_SUCCESS'
export const EMPLOYEE_IMPORT_ERROR     = 'EMPLOYEE_IMPORT_ERROR'

// leave Common Main Types

export const COMMON_MAINTYPES_LIST_REQUEST   = 'COMMON_MAINTYPES_LIST_REQUEST'
export const COMMON_MAINTYPES_LIST_SUCCESS   = 'COMMON_MAINTYPES_LIST_SUCCESS'
export const COMMON_MAINTYPES_LIST_ERROR     = 'COMMON_MAINTYPES_LIST_ERROR'


// Remaining Leave Types
export const REMAININGLEAVE_LIST_REQUEST   = 'REMAININGLEAVE_LIST_REQUEST'
export const REMAININGLEAVE_LIST_SUCCESS   = 'REMAININGLEAVE_LIST_SUCCESS'
export const REMAININGLEAVE_LIST_ERROR     = 'REMAININGLEAVE_LIST_ERROR'



export const COMPENSATION_ADD_SUCCESS  = 'COMPENSATION_ADD_SUCCESS'
export const COMPENSATION_ADD_REQUEST  = 'COMPENSATION_ADD_REQUEST'
export const COMPENSATION_ADD_ERROR    = 'COMPENSATION_ADD_ERROR'

export const COMPENSATION_EDIT_SUCCESS  = 'COMPENSATION_EDIT_SUCCESS'
export const COMPENSATION_EDIT_REQUEST  = 'COMPENSATION_EDIT_REQUEST'
export const COMPENSATION_EDIT_ERROR    = 'COMPENSATION_EDIT_ERROR'

export const COMPENSATION_UPDATE_SUCCESS  = 'COMPENSATION_UPDATE_SUCCESS'
export const COMPENSATION_UPDATE_REQUEST  = 'COMPENSATION_UPDATE_REQUEST'
export const COMPENSATION_UPDATE_ERROR    = 'COMPENSATION_UPDATE_ERROR'

export const COMPENSATION_DELETE_REQUEST  = 'COMPENSATION_DELETE_REQUEST'
export const COMPENSATION_DELETE_SUCCESS  = 'COMPENSATION_DELETE_SUCCESS'
export const COMPENSATION_DELETE_ERROR    = 'COMPENSATION_DELETE_ERROR'

export const COMPENSATION_DP_LIST_REQUEST  = 'COMPENSATION_DP_LIST_REQUEST'
export const COMPENSATION_DP_LIST_SUCCESS   = 'COMPENSATION_DP_LIST_SUCCESS'
export const COMPENSATION_DP_LIST_ERROR     = 'COMPENSATION_DP_LIST_ERROR'

export const COMPENSATION_COAM_DP_LIST_REQUEST   = 'COMPENSATION_COAM_DP_LIST_REQUEST'
export const COMPENSATION_COAM_DP_LIST_SUCCESS   = 'COMPENSATION_COAM_DP_LIST_SUCCESS'
export const COMPENSATION_COAM_DP_LIST_ERROR     = 'COMPENSATION_COAM_DP_LIST_ERROR'

export const EMPLOYEE_EXPORT_LIST_REQUEST   = 'EMPLOYEE_EXPORT_LIST_REQUEST'
export const EMPLOYEE_EXPORT_LIST_SUCCESS   = 'EMPLOYEE_EXPORT_LIST_SUCCESS'
export const EMPLOYEE_EXPORT_LIST_ERROR     = 'EMPLOYEE_EXPORT_LIST_ERROR'


// Job BasicTab

// Job Add API
export const JOB_BASIC_ADD_REQUEST   = 'JOB_BASIC_ADD_REQUEST'
export const JOB_BASIC_ADD_SUCCESS   = 'JOB_BASIC_ADD_SUCCESS'
export const JOB_BASIC_ADD_ERROR     = 'JOB_BASIC_ADD_ERROR'

// Get all Leave Data List

export const LEAVEREQUEST_DATA_LIST_REQUEST   = 'LEAVEREQUEST_DATA_LIST_REQUEST'
export const LEAVEREQUEST_DATA_LIST_SUCCESS   = 'LEAVEREQUEST_DATA_LIST_SUCCESS'
export const LEAVEREQUEST_DATA_LIST_ERROR     = 'LEAVEREQUEST_DATA_LIST_ERROR'


// Candidate Invite Add API
export const CANDIDATE_INVITE_ADD_REQUEST = 'CANDIDATE_INVITE_ADD_REQUEST'
export const CANDIDATE_INVITE_ADD_SUCCESS = 'CANDIDATE_INVITE_ADD_SUCCESS'
export const CANDIDATE_INVITE_ADD_ERROR   = 'CANDIDATE_INVITE_ADD_ERROR'
